# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/utility:${BUILD_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/utility',
        '.']
  env: ['BUILD_VERSION=1.0']

images:
- 'gcr.io/$PROJECT_ID/utility:latest'
- 'gcr.io/$PROJECT_ID/utility:$BUILD_VERSION'