# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/packer',
        '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
        '.']
substitutions:
  _PACKER_VERSION: 1.3.3

images:
- 'gcr.io/$PROJECT_ID/packer:latest'
- 'gcr.io/$PROJECT_ID/packer:$_PACKER_VERSION'